### ISSUE TITLE
Request: Anonymizer

### ISSUE THREAD

**Issue by madkat** [aolszowka/MsBuildProjectReferenceDependencyGraph#2]
As a user, I would like all of my project names to be anonymized so that I can safely share my graph with others.

**Comment by aolszowka** [comment]
I took a stab at it (new optional flag -a,-anonymize, /a, /anonymize) but I am not super happy with the implementation, wanna take a peek?

**Comment by madkat** [comment]
The output is working well. Is there something in particular about the implementation that you do not like?

**Comment by aolszowka** [comment]
Mostly that its limited to 9999 unique projects, also really hacky how I got it to work note this line:

https://github.com/aolszowka/MsBuildProjectReferenceDependencyGraph/blob/9237a7b38c42a3590d51a3924fac652d72ba36b0/MsBuildProjectReferenceDependencyGraph/Anonymizer.cs#L34

Seems really wonky because it'll only work with tokens that start with 0 (so 012ABC work but ABC012) will produce weird results), it'd be nice if my anonymizer class were more generic so that I didn't have to rely on that trim. The problem I was having was trying to figure out how to do it with an enumerator.
